### ISSUE TITLE
Adding shebang line to Run_abSENSE.py

### ISSUE THREAD

**Issue by josuebarrera** [caraweisman/abSENSE#2]
Dear caraweisman,

I would like to ask for a shebang line in Run_abSENSE.py:

`#!/usr/bin/env python`

That way, abSENSE could be easily added to the PATH as an executable. I know it is a silly request, as I could just add the line myself, but I'm looking to include abSENSE as part of a pipeline I'm working on, and having it with a shebang line from the start would really help (the pipeline automatically looks for Run_abSENSE.py in the PATH). 

Best regards,
Josué.

**Comment by caraweisman** [comment]
Not silly - thank you for asking! Just added it. 
Let me know if I can help with anything else.

Cara

**Comment by josuebarrera** [comment]
Dear Cara,

Thank you very much for your quick reply! Could you please move the shebang line at the very start of the python script (before the line containing "from __future__ import print_function")? Otherwise, I don't think it would work as a command-line executable. Thanks again!

Josué.

**Comment by caraweisman** [comment]
Ha, right you are. Sorry, that was brainless of me. Fixed (:

**Comment by josuebarrera** [comment]
It works perfectly fine now, thank you so much!
